package:
  name: "hera"
  version: "0.4.1"

source:
  git_url: http://mathsrv2:8081/edenn/pyhera.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python 3.6.5
    - dask 2.9.0
    - mongoengine 0.18.2
    - xarray 0.14.1
    - pytables 3.4.4
    - scipy 1.3.2

about:
  summary: "Hera"
